### ISSUE TITLE
Error: Could not resolve unknowns: javax.inject:javax.inject:null

### ISSUE THREAD

**Issue by email2vimalraj** [joeferner/node-java-maven#10]
My `package.json` contains this:

```
  "java": {
    "dependencies": [
      {
        "groupId": "org.jboss.weld",
        "artifactId": "weld-osgi-bundle",
        "version": "1.1.4.Final"
      }
    ]
  }
```

and I get the following error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: could not resolve unknowns: javax.inject:javax.inject:null
```

Refer: http://search.maven.org/#artifactdetails%7Corg.jboss.weld%7Cweld-osgi-bundle%7C1.1.4.Final%7Cjar

I believe it is because the error is thrown if there is no version specified in the dependencies. I would suggest that we need not to rely on version.

**Comment by joeferner** [comment]
added test for this dependency. fixed. published v0.0.11.
