### ISSUE TITLE
Error on run.   

### ISSUE THREAD

**Issue by jjmartin** [joeferner/node-java-maven#13]
I'm trying to use this for a build/deploy dependency on https://github.com/awslabs/aws-apigateway-importer

so i installed node-java-maven and added :

```
"java": {
    "dependencies":[
      {
        "groupId": "com.amazonaws",
        "artifactId":"aws-apigateway-importer",
        "version":"1.0.1"
      }
    ]
  }
```

To my package.json.

when i run `.\node_modules\.bin\node-java-maven`,  i get: 

```
...
resolving: org.apache.httpcomponents:httpclient:4.3.3
C:\Projects\MYPROJECT\node_modules\node-java-maven\index.js:352
    throw new Error("Could not resolve property: " + propertyName);
    ^

Error: Could not resolve property: project.parent.version
    at resolveProperty (C:\Projects\MYPROJECT\node_modules\node-java-maven\index.js:352:11)
    at resolveProperty (C:\Projects\MYPROJECT\node_modules\node-java-maven\index.js:349:16)
    at resolveProperty (C:\Projects\MYPROJECT\node_modules\node-java-maven\index.js:349:16)
    at C:\Projects\MYPROJECT\node_modules\node-java-maven\index.js:334:22
    at String.replace (native)
    ...
```

Am I missing something or is there an issue with this package?

**Comment by joeferner** [comment]
Couple of problems that I fixed to make this work.
https://github.com/joeferner/node-java-maven/commit/f593f61aedd71e4281a27ab3c7da4c9d060bec15
https://github.com/joeferner/node-java-maven/commit/a1216fd61b24b29fc986ed21aaeff1c26a1f4da5

These poms use version ranges so you'll need to do something like this...
https://github.com/joeferner/node-java-maven/blob/master/test/com.amazonaws_aws-apigateway-importer_1.0.1.json
to force a version for `com.amazonaws:aws-java-sdk-core`
