### ISSUE TITLE
0.0.11 regression

### ISSUE THREAD

**Issue by ligustah** [joeferner/node-java-maven#15]
Hi,

I just tried updating to 0.0.11 from 0.0.9 and apparently the changes to the substitution logic broke my app. I have this dependency:

``` json
{
        "groupId": "org.apache.pdfbox",
        "artifactId": "pdfbox",
        "version": "1.8.10"
}
```

My program fails to start because it can't find a replacement for $project.version, which is definitely set.

**Comment by joeferner** [comment]
published v0.0.12. Give that a try.

Added test for pdfbox... https://github.com/joeferner/node-java-maven/commit/f593f61aedd71e4281a27ab3c7da4c9d060bec15
