### ISSUE TITLE
Error: Could not resolve property: project.parent.groupId

### ISSUE THREAD

**Issue by gorkagal1983** [joeferner/node-java-maven#23]
I do not know if it is a bug or is my fault but I am having this error in console:

Error: Could not resolve property: project.parent.groupId

My configuration is this:

"java": {
  "repositories": [
    {
      "id": "computing",
      "url": "http://10.32.8.163:8081/artifactory/computing/"
    }
  ],
  "dependencies": [
    {
      "groupId": "com.deustotech.computing",
      "artifactId": "dante",
      "version": "1.0.0"
    }
  ]
}
this artifactId is working obviously in the IntelliJ. I am using the last version 
of the module (0.1.0)

The dependency that is causing the problem is this (core of netlib-java): https://maven.hotlibs.com/com.googlecode.netlib-java.netlib-java/artifact/1.1

I have taken a look to the code and I have modified resolveSubstitutions function and now it works:

function resolveSubstitutions(str, pom, dependency) {
    str = str.replace(/\$\{(.*?)\}/g, function(m, propertyName) {
      if(propertyName == 'project.version' || propertyName == 'version') {
        return pom.version;
      }
      /*if(propertyName == 'project.parent.version') {  //OLD CODE
        return pom.version;
      }*/
      **if(propertyName == 'project.parent.version') { //NEW CODE
        return pom.pomXml.project.parent[0].version[0];
      }
      if(propertyName == 'project.parent.groupId') {
        return pom.pomXml.project.parent[0].groupId[0]
      }**
      var property = resolveProperty(propertyName, pom);
      return property instanceof Array ? property.slice(-1) : property;
    });
    return resolveVersionRange(str, dependency);
  }

Take a look please

**Comment by joeferner** [comment]
Great, thanks. I'll make the change tonight unless you want to submit a PR.

**Comment by gorkagal1983** [comment]
Yep, if you want I can do now the PR, I have ready! You have to give me permissions.

**Comment by joeferner** [comment]
You should be able to submit a PR without permissions. Fork the repo, make the change, submit PR.

**Comment by gorkagal1983** [comment]
PR done!
